export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const VOITURE_ADD="_ADD"
export const VOITURE_REMOVE="VOITURE_REMOVE"
export const VOITURE_EDIT="CONTACT_EDIT"
export const GET_VOITURES="GET_VOITURES"
export const VOITURE_LOADING="VOITURE_LOADING"
export const VOITURE_ERROR="VOITURE_ERROR"
export const ADD_COMMENT="ADD_COMMENT"
export const REMOVE_COMMENT="REMOVE_COMMENT"
export const GET_VOITURE="GET_VOITURE"

